# Generated by Django 2.2.1 on 2020-03-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('gcontent', models.CharField(blank=True, db_column='gContent', max_length=255, null=True)),
                ('vcontent', models.CharField(blank=True, db_column='vContent', max_length=255, null=True)),
                ('e_time', models.CharField(blank=True, max_length=255, null=True)),
                ('s_time', models.CharField(blank=True, max_length=255, null=True)),
                ('msign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('m_title', models.CharField(blank=True, max_length=255, null=True)),
                ('c_time', models.CharField(blank=True, max_length=255, null=True)),
                ('b_time', models.CharField(blank=True, max_length=255, null=True)),
                ('m_place', models.CharField(blank=True, max_length=255, null=True)),
                ('m_content', models.CharField(blank=True, max_length=255, null=True)),
                ('mcreator_id', models.CharField(blank=True, db_column='mCreator_id', max_length=255, null=True)),
                ('mlabel', models.CharField(blank=True, db_column='mLabel', max_length=255, null=True)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('sign', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('department', models.CharField(blank=True, max_length=45, null=True)),
                ('label1', models.CharField(blank=True, max_length=45, null=True)),
                ('label2', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_id', models.ForeignKey(blank=True, db_column='mid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.Meeting')),
                ('u_id', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.User')),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=800, null=True)),
                ('sign', models.CharField(blank=True, max_length=500, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.User')),
            ],
            options={
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='CoCachedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('cached_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.User')),
            ],
            options={
                'db_table': 'co_cached_message',
            },
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_id', models.IntegerField()),
                ('sign', models.PositiveIntegerField(blank=True, null=True)),
                ('admin', models.PositiveIntegerField(blank=True, null=True)),
                ('vote', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.Meeting')),
            ],
            options={
                'db_table': 'meeting_user',
                'unique_together': {('m_id', 'cu_id')},
            },
        ),
    ]
