# Generated by Django 2.2.1 on 2020-04-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('gcontent', models.CharField(blank=True, db_column='gContent', max_length=255, null=True)),
                ('vcontent', models.CharField(blank=True, db_column='vContent', max_length=255, null=True)),
                ('e_time', models.CharField(blank=True, max_length=255, null=True)),
                ('s_time', models.CharField(blank=True, max_length=255, null=True)),
                ('msign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('m_title', models.CharField(blank=True, max_length=255, null=True)),
                ('c_time', models.CharField(blank=True, max_length=255, null=True)),
                ('b_time', models.CharField(blank=True, max_length=255, null=True)),
                ('m_place', models.CharField(blank=True, max_length=255, null=True)),
                ('m_content', models.CharField(blank=True, max_length=255, null=True)),
                ('mcreator_id', models.CharField(blank=True, db_column='mCreator_id', max_length=255, null=True)),
                ('mlabel', models.CharField(blank=True, db_column='mLabel', max_length=255, null=True)),
                ('status', models.NullBooleanField()),
                ('limits', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.BooleanField(default=False, null=True)),
                ('sign_time', models.DateTimeField(auto_now=True)),
                ('admin', models.BooleanField(default=False, null=True)),
                ('vote', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=255)),
                ('image', models.ImageField(null=True, upload_to='avatarImg')),
                ('sex', models.NullBooleanField()),
                ('sign', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('label1', models.CharField(blank=True, max_length=45, null=True)),
                ('label2', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Votetheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('theme_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Voteuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=32, null=True)),
                ('votetheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Votetheme', to_field='theme_id')),
            ],
        ),
        migrations.CreateModel(
            name='Voteoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('votetheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Votetheme', to_field='theme_id')),
            ],
        ),
        migrations.CreateModel(
            name='Usersign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stime', models.DateTimeField(auto_now_add=True)),
                ('Snumber', models.CharField(max_length=32)),
                ('Sdepartment', models.CharField(max_length=255)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapi.Membership')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(through='userapi.Membership', to='userapi.User'),
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(blank=True, max_length=255, null=True)),
                ('award_time', models.DateTimeField(auto_now=True)),
                ('award_member', models.CharField(blank=True, max_length=32, null=True)),
                ('award_leval', models.CharField(blank=True, max_length=32, null=True)),
                ('award_type', models.CharField(blank=True, max_length=32, null=True)),
                ('award_membership', models.ManyToManyField(to='userapi.User')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=800, null=True)),
                ('sign', models.CharField(blank=True, max_length=500, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.User')),
            ],
            options={
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(blank=True, max_length=255, null=True)),
                ('Dtime', models.DateTimeField(auto_now_add=True)),
                ('Dstyle', models.CharField(blank=True, max_length=32, null=True)),
                ('Dsize', models.CharField(blank=True, max_length=32, null=True)),
                ('Dpath', models.CharField(blank=True, max_length=255, null=True)),
                ('Dstatus', models.BooleanField(default=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='CoCachedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('cached_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userapi.User')),
            ],
            options={
                'db_table': 'co_cached_message',
            },
        ),
    ]
