# Generated by Django 2.2.1 on 2020-03-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.PositiveIntegerField(blank=True, null=True)),
                ('admin', models.PositiveIntegerField(blank=True, null=True)),
                ('vote', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.User')),
            ],
        ),
        migrations.DeleteModel(
            name='MeetingUser',
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(through='userapi.Membership', to='userapi.User'),
        ),
    ]
