# Generated by Django 2.2.1 on 2020-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_auto_20200307_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='limits',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='membership',
            name='sign_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
