# Generated by Django 2.2.1 on 2020-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_auto_20200317_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='sign',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
