# Generated by Django 2.2.1 on 2020-03-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_auto_20200317_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(blank=True, max_length=255, null=True)),
                ('award_time', models.DateTimeField(auto_now=True)),
                ('award_member', models.CharField(blank=True, max_length=32, null=True)),
                ('award_leval', models.CharField(blank=True, max_length=32, null=True)),
                ('award_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapi.Membership')),
            ],
        ),
    ]
